version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mehfil_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/mehfil
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: myverystrongsecretkey
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  worker:
    build: .
    container_name: mehfil_worker
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mehfil
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - /app/node_modules
    command: node workers/taskWorker.js
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mehfil_mongo
    ports:
      - "27018:27017"
    volumes:
      - mehfil_mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: mehfil_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mehfil_mongo_data:
